export const FIRING_TYPE_CONDITIONS = {
    "NO_INFORMATION": "Keine Angabe",
    "GEOTHERMAL": "Erdwärme",
    "SOLAR_HEATING": "Solar",
    "PELLET_HEATING": "Holzpellets",
    "GAS": "Gas",
    "OIL": "Öl",
    "DISTRICT_HEATING": "Fernwärme",
    "ELECTRICITY": "Strom",
    "COAL": "Kohle",
    "NATURAL_GAS_LIGHT": "Erdgas leicht",
    "NATURAL_GAS_HEAVY": "Erdgas schwer",
    "LIQUID_GAS": "Flüssiggas",
    "STEAM_DISTRICT_HEATING": "Fernwärme-Dampf",
    "WOOD": "Holz",
    "WOOD_CHIPS": "Holz-Hackschnitzel",
    "COAL_COKE": "Kohle/Koks",
    "LOCAL_HEATING": "Nahwärme",
    "HEAT_SUPPLY": "Wärmelieferung",
    "BIO_ENERGY": "Bioenergie",
    "WIND_ENERGY": "Windenergie",
    "HYDRO_ENERGY": "Wasserenergie",
    "ENVIRONMENTAL_THERMAL_ENERGY": "Umweltwärme",
    "COMBINED_HEAT_AND_POWER_FOSSIL_FUELS": "KWK fossil",
    "COMBINED_HEAT_AND_POWER_RENEWABLE_ENERGY": "KWK erneuerbar",
    "COMBINED_HEAT_AND_POWER_REGENERATIVE_ENERGY": "KWK regenerativ",
    "COMBINED_HEAT_AND_POWER_BIO_ENERGY": "KWK bio"
};
